stages:
  - commit_to_github

commit_to_github:
  stage: commit_to_github
  script:
    # Clone o repositório do GitHub diretamente
    - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/docs.git
    - cd docs

    # Configure o usuário Git
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"

    # Adicione suas alterações
    - git add .
    
    # Verifique se há alterações antes de tentar fazer o commit
    - |
      if ! git diff-index --quiet HEAD; then
        git commit -m "Auto commit from GitLab CI"
        git push origin main
      else
        echo "No changes to commit."
      fi
  only:
    - main
