stages:
  - sync_to_github

sync_to_github:
  stage: sync_to_github
  script:
    # Configure o usuário Git para commits
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"

    # Verifique o estado do repositório GitLab
    - echo "Status do repositório GitLab:"
    - git status

    # Verifique as branches do repositório GitLab
    - echo "Branches do repositório GitLab:"
    - git branch

    # Crie um diretório temporário e clone o repositório GitHub
    - mkdir -p temp_repo
    - cd temp_repo
    - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/docs.git

    # Navegue para o diretório clonado
    - cd docs

    # Verifique o status e branches do repositório GitHub
    - echo "Status do repositório GitHub:"
    - git status
    - echo "Branches do repositório GitHub:"
    - git branch

    # Compare o histórico de commits
    - echo "Histórico de commits do GitHub:"
    - git log --oneline
    - cd ..
    - echo "Histórico de commits do GitLab:"
    - cd <path_to_local_repo>
    - git log --oneline

    # Compare o conteúdo dos repositórios
    - echo "Comparando conteúdos dos repositórios:"
    - diff -r docs <path_to_local_repo>

    # Volte ao repositório principal
    - cd ..
    - rm -rf temp_repo

    # Adicione e envie alterações para o GitHub se houver
    - git add .
    - |
      if ! git diff-index --quiet HEAD; then
        git commit -m "Sync from GitLab CI"
        git push github main
      else
        echo "Nenhuma alteração para commitar."
      fi
  only:
    - main
