stages:
  - commit_to_github

commit_to_github:
  stage: commit_to_github
  script:
    # Configure o usuário Git
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"

    # Crie um diretório temporário para o repositório GitHub
    - mkdir temp_repo
    - cd temp_repo

    # Clone o repositório GitHub no diretório temporário
    - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/docs.git .
    
    # Adicione suas alterações
    - git add .
    
    # Verifique se há alterações antes de tentar fazer o commit
    - |
      if ! git diff-index --quiet HEAD; then
        git commit -m "Auto commit from GitLab CI"
        # Empurre as alterações para o GitHub
        git push origin main
      else
        echo "No changes to commit."
      fi
  only:
    - main
