stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git config --global user.email "gabrielestefono@hotmail.com"
    - git config --global user.name "gabrielestefono"
    - git remote add github https://$GITHUB_TOKEN@github.com/gabrielestefono/docs.git
    - git fetch origin main
    - git checkout main || git checkout -b main
    - git push github main
  only:
    - main
