stages:
  - sync_to_github

sync_to_github:
  stage: sync_to_github
  script:
    # Configure o usuário Git para commits
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"

    # Verifique o estado do repositório
    - echo "Verificando o estado do repositório:"
    - git status
    
    # Verifique os remotos configurados
    - echo "Verificando remotos:"
    - git remote -v

    # Adicione o repositório GitHub como remoto se não existir
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/docs.git || true

    # Faça um pull para garantir que o repositório está atualizado
    - echo "Fazendo pull do repositório GitHub:"
    - git pull github main || echo "Não foi possível fazer pull; talvez o repositório esteja desatualizado."

    # Adicione todas as alterações feitas no repositório GitLab
    - git add .
    
    # Verifique as diferenças para garantir que há alterações
    - echo "Verificando diferenças antes do commit:"
    - git diff --cached

    # Commit e push para o repositório GitHub se houver alterações
    - |
      if ! git diff-index --quiet HEAD; then
        git commit -m "Sync from GitLab CI"
        echo "Fazendo push para o GitHub:"
        git push github main
      else
        echo "Nenhuma alteração para commitar."
      fi

    # Mostre o log dos commits para diagnóstico
    - echo "Mostrando histórico de commits:"
    - git log --oneline
  only:
    - main
